kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
name: image-pos
namespace: example-multistage-build
spec:
nodeSelector: null
output:
to:
kind: DockerImage
name: 'quay.io/fdemeloj1/simulacroquarkus:latest'
pushSecret:
name: dockerhub
resources: {}
successfulBuildsHistoryLimit: 5
failedBuildsHistoryLimit: 5
strategy:
type: Docker
dockerStrategy:
from:
kind: ImageStreamTag
namespace: example-multistage-build
name: 'imagestreamone:latest'
postCommit: {}
source:
type: Dockerfile
dockerfile: >
# Test Francisco 8th
FROM registry.access.redhat.com/ubi8/openjdk-11:1.15-1.1682059493
RUN touch /opt/murder_by_numbers.txt
RUN echo "This image combines the input from another image in a multistage
build, listening to The Police" > /opt/murder_by_numbers.txt

EXPOSE 8080
USER 185
ENV AB_JOLOKIA_OFF=""


ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0
-Djava.util.logging.manager=org.jboss.logmanager.LogManager"


ENV JAVA_APP_JAR="/deployments/application.jar"
images:
- from:
kind: ImageStreamTag
namespace: example-multistage-build
name: 'imagestreamone:latest'
paths:
- sourcePath: /home/jboss/target/quarkus-app/lib/application.jar
destinationDir: deployments/
runPolicy: Serial
